language: ruby
rvm:
  - "2.1.3"
env:
  - DB=postgresql
  
os: "osx"

secure: "e/Av/7dTHJK3i47eC1LAB4frwiiqaZxx5iC+Uo22HrRdWYSNx5qp5DG7HkP9tPm3s4EX5S+lbws6bUTNlBGNqAuZjXpBYbcaiV3TFjExTFj4Ef08MVjA5H2bF5dqBK7GOscdhL7YW4aCGq0riiX+D4ARSZC0lykAf/rUrEAVzn2NC7ucRcEYeT/zczb1uBUu+lpnHbGRPEytLHG0cL2QNkCQVL/PKciIIx18uUPPhPEDL8FljRg54PRHgBqFUYsusNiXoL7zUTTtwXmUBsrYQRnqC5rFuMvCrndX0KMpOiMVfj2NdOleSO7ZCrQFZEE0ANCJFlKsFHri/a31dcIJH5+Nac4XSAGipsXNIiJRxFDdec+zCLQws38VcbvH6Wq3ulEWGoEeA7ZiEolS+Jh6alS0rN6Qf40x+WwsT/rd5OZvR0UhrFR+78tKazZhpB9tDVbsZDFsmZzBNZXxdn8nCydiM04uL16+kkun8HFSm5NRKz4hxguyp1mW5pOLcJrXGmMkjYpH6scxMPAeJuedk/RnUknixq1XQ1GrYIzE76BfRoUdVHtMbalZ3xAx6CF58hEzT1u3W3XHjPMbFNOMXLIbeMtIX3zQfdmuhyPmaSWbeNyrtrI8WP0DX84Fetfy0lCi26qTqc3i5GAX29atkzLllsffcyFDP8FciklC6xA="

